### ISSUE TITLE
CMake: doesn't install anything if -DTWEEDLEDUM_PYBINDS=OFF

### ISSUE THREAD

**Issue by drewrisinger** [boschmitt/tweedledum#129]
Nothing is installed if the CMake flag ``-DTWEEDLEDUM_PYBINDS=OFF``. (i.e. ``make install`` does nothing after configuring & building).

I'm not the most well-versed in CMake/C++ library building, but it seems to me that at least the ``*.so`` should be installed if the python bindings are not installed.

Relevant code:
https://github.com/boschmitt/tweedledum/blob/1c331a076fa137295193a10e0ed664603ae80c21/CMakeLists.txt#L44-L59

**Comment by boschmitt** [comment]
This is due to the fact that, originally, `tweedledum` was a header-only C++ library. Now, this is not the case anymore; Mainly because to do python bindings I needed a shared library.

I will have a look into this and find the best way to make it available as a C++ library.

**Comment by drewrisinger** [comment]
Closing b/c after the update to v1.1.0 the *.h files and ``libtweedledum.a`` are installed to the output.
