### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by iyanmv** [boschmitt/tweedledum#169]
### Describe the bug
Cannot build the C++ library or the python package from source code.

### Reproducible example code
Both
```
git clone https://github.com/boschmitt/tweedledum.git
cd tweedledum
mkdir build && cd build
cmake ..
make
```
and
```
git clone https://github.com/boschmitt/tweedledum.git
cd tweedledum
python setup.py build
```
fail to compile.

### Information
- **tweedledum version**: v1.1.1 and master branch
- **Python version**: 3.10.1
- **C++ compiler**: gcc 11.1.0
- **Operating system**: Arch Linux

[CMakeError.log](https://github.com/boschmitt/tweedledum/files/7703386/CMakeError.log)
[CMakeOutput.log](https://github.com/boschmitt/tweedledum/files/7703387/CMakeOutput.log)

**Comment by iyanmv** [comment]
Seems that the issue is caused because of my local version of `fmt` (8.0.1). If I used version 7.0.3 included in the tarball, I can compile. But of course, both ninja and unix makefiles by default try to use the local one.

**Comment by boschmitt** [comment]
> Seems that the issue is caused because of my local version of `fmt` (8.0.1). If I used version 7.0.3 included in the tarball, I can compile. But of course, both ninja and unix makefiles by default try to use the local one.

Thanks for letting me know about it. I will look into it.

**Comment by iyanmv** [comment]
Any news about this?

**Comment by boschmitt** [comment]
> Any news about this?

Sorry for the late reply. I will fix this on the coming week together with a bunch of other fixes.

**Comment by iyanmv** [comment]
Thanks! ;) Looking forward for those patches.
