### ISSUE TITLE
Gray synthesis with no parities

### ISSUE THREAD

**Issue by msoeken** [boschmitt/tweedledum#18]
The test case in branch `msoeken/gray-synth-segfault` in e5e049c leads to a segmentation fault.

**Comment by boschmitt** [comment]
I wonder what the best behaviour for this case should be. Should we ``assert`` the the input is not empty, or, as you seem to assume, simply return a network without any gates.

**Comment by msoeken** [comment]
I think we should simply return an empty network with as many qubits as requested by the first argument. This method could be used in some other algorithm, so the case in which there is no parity term can occur in corner cases.
