### ISSUE TITLE
Push a release with python 3.9 wheels

### ISSUE THREAD

**Issue by mtreinish** [boschmitt/tweedledum#88]
Python 3.9 has been out for ~1 month now. It would be good if there was a tweedledum release that had a precompiled binary wheel with python 3.9. Looking at the CI setup for building and publishing wheels this will be done automatically on the next release since the latest cibuildwheel 1.6.x has support for 3.9 so it's just a matter of pushing a new release (or retriggering a build for the existing release).

**Comment by boschmitt** [comment]
Thanks for the heads up. This is done.
